name: Renovate
on:
  schedule:
    - cron: '0 8 * * MON'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level: (info|warn|error|fatal|debug)'
        required: true
        default: 'info'

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run Renovate
        uses: renovatebot/github-action@80eaf969abf68ad62aa94d9ab392421b31621634 # v40.3.4
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
        env:
          LOG_LEVEL: "${{ github.event.inputs.logLevel || 'debug' }}"
