name: Renovate
on:
  schedule:
    - cron: '0 8 * * MON'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level: (info|warn|error|fatal|debug)'
        required: true
        default: 'info'

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Run Renovate
        uses: renovatebot/github-action@21d88b0bf0183abcee15f990011cca090dfc47dd # v40.1.12
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
        env:
          LOG_LEVEL: "${{ github.event.inputs.logLevel || 'debug' }}"
